#!/usr/bin/env bash
# ============================================================================
# backup-codex.sh — Backup & Restore Codex CLI Configuration
# ============================================================================
#
# OVERVIEW
#   Syncs your Codex CLI configuration (instructions, config.toml, agents,
#   skills, rules, memories) across machines via zip archives or
#   GitHub Gists.
#
# USAGE
#   ./backup-codex.sh                    # Create zip backup (default)
#   ./backup-codex.sh --zip    | -z      # Create zip in ~/backups/codex/
#   ./backup-codex.sh --gist   | -g      # Upload to a secret GitHub Gist
#   ./backup-codex.sh --both   | -b      # Create zip AND upload to Gist
#   ./backup-codex.sh --restore| -r <zip># Restore from a zip backup
#   ./backup-codex.sh --list   | -l      # List existing backups
#   ./backup-codex.sh --help   | -h      # Show help
#
# WHAT GETS BACKED UP
#   AGENTS.md          Global instructions applied to all projects
#   RTK.md             Token-optimization CLI proxy reference
#   CODEX_SETUP.md     Codex setup notes
#   CODEX_WORKFLOWS.md Codex workflow notes
#   config.toml        Model, profiles, MCP servers, sandbox/approval settings
#   agents/            Custom subagent definitions (deep-reasoner, fast-worker)
#   skills/            Custom skills (skills/omarchy is a symlink into
#                      ~/.local/share/omarchy; zip follows it and stores the
#                      target's files, so the archive is self-contained)
#   rules/             Execution policy rules (default.rules)
#   memories/          MEMORY.md and summaries
#   Excluded inside targets: skills/.system (Codex's bundled built-in skills,
#   regenerated by Codex) and any other hidden files or directories.
#
# WHAT IS NOT BACKED UP
#   auth.json              OAuth/API credentials (machine-specific, sensitive)
#   sessions/, history.jsonl, session_index.jsonl
#                          Conversation transcripts and history (large, private)
#   *.sqlite               Logs, state, thread history, memories index, goals, queue
#   packages/              Downloaded packages (large, regenerable)
#   plugins/, cache/, models_cache.json, vendor_imports/
#                          Regenerable caches and vendored imports
#   .tmp/, tmp/, shell_snapshots/, log/, ipc/, the lock dirs,
#   installation_id, version.json, .codex-global-state.json*
#                          Runtime state and scratch data
#
# CROSS-MACHINE SYNC WORKFLOW
#   Machine A (backup):
#     ./backup-codex.sh --gist          # uploads to GitHub Gist
#
#   Machine B (restore):
#     gh gist clone <gist-url> /tmp/codex-restore
#     # Unflatten files back into ~/.codex/
#
#   Or via zip + scp/Drive:
#     # Machine A
#     ./backup-codex.sh --zip
#     scp ~/backups/codex/codex-backup-*.zip machineB:~/
#     # Machine B
#     ./backup-codex.sh --restore ~/codex-backup-*.zip
#
# SAFETY
#   - --restore creates a pre-restore safety backup (codex-pre-restore-*.zip)
#     before overwriting, so you can always roll back
#   - Asks for explicit [y/N] confirmation before restoring
#   - Shows zip contents before extraction
#
# REQUIREMENTS
#   zip     Required for --zip, --both, --restore
#   unzip   Required for --restore
#   gh      Required for --gist, --both (https://cli.github.com)
#
# ENVIRONMENT VARIABLES
#   CODEX_CONFIG_DIR    Override config path (default: ~/.codex)
#   BACKUP_DIR           Override backup path (default: ~/backups/codex)
#
# ============================================================================

set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────────────────
# CODEX_CONFIG_DIR: Where Codex CLI stores its configuration.
# BACKUP_DIR:        Where zip backups are written to.
# TIMESTAMP:         Used in backup filenames for uniqueness and chronological sorting.
CODEX_CONFIG_DIR="${CODEX_CONFIG_DIR:-${HOME}/.codex}"
BACKUP_DIR="${BACKUP_DIR:-${HOME}/backups/codex}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
ZIP_NAME="codex-backup-${TIMESTAMP}.zip"

# ─── Backup Targets ──────────────────────────────────────────────────────────
# Files and directories to include in backups. Each entry is relative to
# CODEX_CONFIG_DIR. Missing targets are silently skipped (e.g., if a user
# hasn't created memories/ or rules/ yet).
BACKUP_TARGETS=(
  "AGENTS.md"          # Global instructions applied to all projects
  "RTK.md"             # Token-optimization CLI proxy reference
  "CODEX_SETUP.md"     # Codex setup notes
  "CODEX_WORKFLOWS.md" # Codex workflow notes
  "config.toml"        # Model, profiles, MCP servers, sandbox/approval settings
  "agents"             # Custom subagent definitions (deep-reasoner, fast-worker)
  "skills"             # Custom skills (skills/omarchy symlink is followed)
  "rules"              # Execution policy rules
  "memories"           # MEMORY.md and summaries
)

# Codex's bundled built-in skills; it regenerates them.
EXCLUDE_PATHS=("skills/.system/*")

# ─── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}ℹ${NC}  $*"; }
success() { echo -e "${GREEN}✅${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}❌${NC} $*" >&2; }

# ─── Helpers ──────────────────────────────────────────────────────────────────

# Verify the Codex config directory exists before any operation.
check_codex_config() {
  if [[ ! -d "${CODEX_CONFIG_DIR}" ]]; then
    error "Codex config directory not found: ${CODEX_CONFIG_DIR}"
    error "Is Codex CLI installed? Config is created on first run."
    exit 1
  fi
}

# Scan BACKUP_TARGETS and return only the ones that actually exist on disk.
collect_files() {
  local found=()
  for target in "${BACKUP_TARGETS[@]}"; do
    local path="${CODEX_CONFIG_DIR}/${target}"
    if [[ -e "${path}" ]]; then
      found+=("${target}")
    fi
  done
  echo "${found[@]}"
}

# Print a visual summary of what will be backed up.
print_backup_summary() {
  local files=("$@")
  echo ""
  echo -e "${BOLD}📦 Codex CLI Backup Summary${NC}"
  echo "─────────────────────────────────────"
  echo -e "  Source:  ${CODEX_CONFIG_DIR}"
  echo ""
  for f in "${files[@]}"; do
    local path="${CODEX_CONFIG_DIR}/${f}"
    if [[ -d "${path}" ]]; then
      local count
      # -L follows symlinks like zip; hidden paths are skipped like zip's '*/.*'
      count=$(find -L "${path}" -type f -not -path "${path}/.*" -not -path "${path}/*/.*" 2>/dev/null | wc -l)
      echo -e "  ${GREEN}✓${NC} ${f}/  (${count} files)"
    else
      local size
      size=$(du -h "${path}" 2>/dev/null | cut -f1)
      echo -e "  ${GREEN}✓${NC} ${f}  (${size})"
    fi
  done
  echo "─────────────────────────────────────"
  echo ""
}

# ─── Zip Backup ───────────────────────────────────────────────────────────────
# Creates a timestamped zip archive in ~/backups/codex/.
# Excludes: .DS_Store, hidden dotfiles, skills/.system (built-in skills)

do_zip() {
  check_codex_config

  if ! command -v zip &>/dev/null; then
    error "'zip' is not installed. Install it with: sudo apt install zip"
    exit 1
  fi

  local files
  read -ra files <<< "$(collect_files)"

  if [[ ${#files[@]} -eq 0 ]]; then
    error "No Codex config files found to back up."
    exit 1
  fi

  print_backup_summary "${files[@]}"

  mkdir -p "${BACKUP_DIR}"
  local zip_path="${BACKUP_DIR}/${ZIP_NAME}"

  # Zip from within the config directory so paths inside the archive
  # are relative (config.toml, not ~/.codex/config.toml)
  (
    cd "${CODEX_CONFIG_DIR}"
    zip -r "${zip_path}" "${files[@]}" -x '*.DS_Store' '*/.*' "${EXCLUDE_PATHS[@]}"
  )

  echo ""
  success "Zip backup created: ${zip_path}"
  echo -e "  Size: $(du -h "${zip_path}" | cut -f1)"
  echo ""

  # Show recent backups if more than one exists, so the user can track history
  local backup_count
  backup_count=$(find "${BACKUP_DIR}" -name "codex-backup-*.zip" -type f | wc -l)
  if [[ "${backup_count}" -gt 1 ]]; then
    info "You have ${backup_count} backups in ${BACKUP_DIR}"
    echo "  Latest 5:"
    find "${BACKUP_DIR}" -name "codex-backup-*.zip" -type f -printf '    %T@ %p\n' \
      | sort -rn | head -5 | while read -r _ path; do
        echo -e "    ${path}  ($(du -h "${path}" | cut -f1))"
      done
    echo ""
  fi
}

# ─── Gist Backup ─────────────────────────────────────────────────────────────
# Uploads config to a secret GitHub Gist for cross-machine sync.
#
# Gist limitations:
#   - No directory support — files are flattened with __ separators
#     e.g. rules/ecc/common/testing.md → rules__ecc__common__testing.md
#   - Gists have a soft size limit (~10MB) — fine for config
#
# Requires:
#   - gh CLI installed and authenticated (gh auth login)
#
# To restore from a Gist:
#   gh gist clone <url> /tmp/codex-restore
#   # Manually unflatten the __ separator files back into directories
#   # Or use --restore with a zip backup instead (recommended)

do_gist() {
  check_codex_config

  if ! command -v gh &>/dev/null; then
    error "'gh' CLI is not installed."
    echo "  Install: https://cli.github.com"
    echo "  Then run: gh auth login"
    exit 1
  fi

  # Verify GitHub authentication before proceeding
  if ! gh auth status &>/dev/null 2>&1; then
    error "Not authenticated with GitHub. Run: gh auth login"
    exit 1
  fi

  local files
  read -ra files <<< "$(collect_files)"

  if [[ ${#files[@]} -eq 0 ]]; then
    error "No Codex config files found to back up."
    exit 1
  fi

  print_backup_summary "${files[@]}"

  # Flatten directory structure for Gist compatibility.
  # Gists are flat file lists — no subdirectories allowed.
  # Convention: path separators become __ (double underscore)
  local temp_dir
  temp_dir=$(mktemp -d)
  trap 'rm -rf "${temp_dir}"' EXIT

  for f in "${files[@]}"; do
    local path="${CODEX_CONFIG_DIR}/${f}"
    if [[ -d "${path}" ]]; then
      find "${path}" -type f | while read -r file; do
        local relative="${file#"${CODEX_CONFIG_DIR}/"}"
        local flat_name="${relative//\//__}"
        cp "${file}" "${temp_dir}/${flat_name}"
      done
    else
      cp "${path}" "${temp_dir}/${f}"
    fi
  done

  info "Uploading to GitHub Gist..."
  echo ""

  local gist_files=()
  for file in "${temp_dir}"/*; do
    [[ -f "${file}" ]] && gist_files+=("${file}")
  done

  if [[ ${#gist_files[@]} -eq 0 ]]; then
    error "No files to upload."
    exit 1
  fi

  local gist_url
  gist_url=$(gh gist create \
    --desc "Codex CLI Config Backup — ${TIMESTAMP}" \
    "${gist_files[@]}" 2>&1)

  echo ""
  success "Gist created: ${gist_url}"
  echo ""
  echo -e "  ${BOLD}To restore from this gist later:${NC}"
  echo "  gh gist clone ${gist_url} /tmp/codex-restore"
  echo "  # Then copy files back to ~/.codex/"
  echo ""
}

# ─── Restore ──────────────────────────────────────────────────────────────────
# Restores config from a zip backup file.
#
# Safety features:
#   1. Shows zip contents before extracting (so you can verify)
#   2. Asks for explicit [y/N] confirmation
#   3. Creates a pre-restore safety backup (codex-pre-restore-*.zip)
#      so you can always roll back if something goes wrong
#   4. Extracts with -o (overwrite) into the config directory
#
# Usage:
#   ./backup-codex.sh --restore ~/backups/codex/codex-backup-20260713.zip
#   ./backup-codex.sh -r /tmp/transferred-backup.zip
#
# After restore:
#   Restart Codex CLI to pick up the restored configuration.

do_restore() {
  local zip_file="$1"

  if [[ ! -f "${zip_file}" ]]; then
    error "Zip file not found: ${zip_file}"
    exit 1
  fi

  echo ""
  echo -e "${BOLD}🔄 Restore Codex CLI Config${NC}"
  echo "─────────────────────────────────────"
  echo -e "  Source: ${zip_file}"
  echo -e "  Target: ${CODEX_CONFIG_DIR}"
  echo ""

  # Preview: show what's inside the zip before extracting
  info "Contents of backup:"
  unzip -l "${zip_file}" | tail -n +4 | head -n -2 | while read -r line; do
    echo "    ${line}"
  done
  echo ""

  # Require explicit confirmation before overwriting
  echo -e "${YELLOW}This will overwrite existing Codex CLI config files.${NC}"
  read -rp "Continue? [y/N] " confirm
  if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
    info "Restore cancelled."
    exit 0
  fi

  # Safety: back up current config before overwriting.
  # This means you can always roll back with:
  #   ./backup-codex.sh --restore ~/backups/codex/codex-pre-restore-*.zip
  if [[ -d "${CODEX_CONFIG_DIR}" ]]; then
    local pre_restore_backup="${BACKUP_DIR}/codex-pre-restore-${TIMESTAMP}.zip"
    mkdir -p "${BACKUP_DIR}"
    info "Backing up current config first → ${pre_restore_backup}"
    (
      cd "${CODEX_CONFIG_DIR}"
      local current_files
      read -ra current_files <<< "$(collect_files)"
      if [[ ${#current_files[@]} -gt 0 ]]; then
        zip -r "${pre_restore_backup}" "${current_files[@]}" -x '*.DS_Store' "${EXCLUDE_PATHS[@]}" 2>/dev/null || true
      fi
    )
  fi

  # Extract into the config directory (overwrite existing files)
  mkdir -p "${CODEX_CONFIG_DIR}"
  unzip -o "${zip_file}" -d "${CODEX_CONFIG_DIR}"

  echo ""
  success "Restore complete! Restart Codex CLI to apply changes."
  echo ""
}

# ─── List Backups ─────────────────────────────────────────────────────────────
# Show all existing backups in ~/backups/codex/, sorted newest first.
#
# Usage:
#   ./backup-codex.sh --list

do_list() {
  if [[ ! -d "${BACKUP_DIR}" ]]; then
    info "No backups found. Run './backup-codex.sh --zip' to create one."
    exit 0
  fi

  local backups
  backups=$(find "${BACKUP_DIR}" -name "codex-*.zip" -type f 2>/dev/null | sort -r)

  if [[ -z "${backups}" ]]; then
    info "No backups found in ${BACKUP_DIR}"
    exit 0
  fi

  echo ""
  echo -e "${BOLD}📋 Codex CLI Backups${NC}"
  echo "─────────────────────────────────────"
  while IFS= read -r path; do
    local size
    size=$(du -h "${path}" | cut -f1)
    local basename
    basename=$(basename "${path}")
    echo -e "  ${basename}  (${size})"
  done <<< "${backups}"
  echo "─────────────────────────────────────"
  echo ""
  echo "  Restore with: ./backup-codex.sh --restore <path>"
  echo ""
}

# ─── Usage ────────────────────────────────────────────────────────────────────

usage() {
  echo ""
  echo -e "${BOLD}backup-codex.sh${NC} — Backup & restore Codex CLI configuration"
  echo ""
  echo "Usage:"
  echo "  ./backup-codex.sh              Create a zip backup (default)"
  echo "  ./backup-codex.sh --zip   -z   Create a zip backup in ~/backups/codex/"
  echo "  ./backup-codex.sh --gist  -g   Upload to a secret GitHub Gist"
  echo "  ./backup-codex.sh --both  -b   Create zip AND upload to Gist"
  echo "  ./backup-codex.sh --restore -r <zip>  Restore from a zip backup"
  echo "  ./backup-codex.sh --list  -l   List existing backups"
  echo "  ./backup-codex.sh --help  -h   Show this help"
  echo ""
  echo "Backed up:"
  echo "  AGENTS.md, RTK.md, CODEX_SETUP.md, CODEX_WORKFLOWS.md, config.toml,"
  echo "  agents/, skills/ (minus skills/.system), rules/, memories/"
  echo ""
  echo "NOT backed up (secrets, caches, transcripts):"
  echo "  auth.json, sessions/, history.jsonl, session_index.jsonl, *.sqlite,"
  echo "  packages/, plugins/, cache/, models_cache.json, vendor_imports/,"
  echo "  tmp/, shell_snapshots/, log/, ipc/, locks, version.json"
  echo ""
  echo "Environment:"
  echo "  CODEX_CONFIG_DIR    Override config dir  (default: ~/.codex)"
  echo "  BACKUP_DIR          Override backup dir  (default: ~/backups/codex)"
  echo ""
  echo "Examples:"
  echo "  ./backup-codex.sh --zip                              # Local backup"
  echo "  ./backup-codex.sh --gist                             # Sync via GitHub"
  echo "  ./backup-codex.sh --restore ~/backups/codex/codex-backup-20260713.zip"
  echo ""
}

# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
  local mode="${1:---zip}"

  case "${mode}" in
    --zip|-z)
      do_zip
      ;;
    --gist|-g)
      do_gist
      ;;
    --both|-b)
      do_zip
      do_gist
      ;;
    --restore|-r)
      if [[ -z "${2:-}" ]]; then
        error "Please provide a zip file path."
        echo "  Usage: ./backup-codex.sh --restore <path-to-zip>"
        exit 1
      fi
      do_restore "$2"
      ;;
    --list|-l)
      do_list
      ;;
    --help|-h)
      usage
      ;;
    *)
      error "Unknown option: ${mode}"
      usage
      exit 1
      ;;
  esac
}

main "$@"
